配置统计配置表
@startuml
start
    :配置基础属性;
    :选择需要统计的字段;
     if (是否总单?) then (yes)
        ->根据模式、公式类型;
        :获取细单回填表;
         if (需要统计的字段是否在细单回填表中?) then(no)
           stop
         endif
     else(no)
        :获取计费基础属性;
         if (需要统计的字段是否计费基础属性中?) then(no)
         stop
         endif;
     endif;
     ->根据模式、公式类型;
     :查看统计的属性是否存在;
     :不存在则新增,存在则更新;
stop
@enduml