配置计费公式表
@startuml
start
    :配置公式名与公式代码;
    :查看可用公式来源字段;
     if (是否总单?) then (yes)
        ->根据模式、公式类型;
        :获取细单回填字段;
    else(no)
        :获取运费基础字段;
    endif;
    ->根据分组配置;
    :获取运价表字段;
    ->根据模式、公式类型;
    :获取对应统计配置字段;
    ->根据上述获取字段组装公式;
    :公式编译;
    if(编译成功？) then (yes)
        ->根据模式、公式类型;
       :1.更新公式来源表
       2.保存并刷新上下文;
    else(no)
    endif
stop
@enduml