配置表
@startuml
start
     if (是否总单?) then (yes)
        ->根据模式、公式类型;
        :获取细单回填字段;
    else(no)
        :获取运费基础字段;
    endif;
    ->选择配置类型：1-运价表依据、2-分组依据、0-所有;
    :获取运价表字段;
    :选择需要配置的字段;
    ->提交;
    :更新;
stop
@enduml