配置回填字段表
@startuml
start
    :获取可回填的字段;
     if (是否总单?) then (yes)
        ->根据模式、公式类型;
        :获取细单回填字段;
    else(no)
        :获取运费基础字段;
    endif;
    ->根据分组配置;
    :获取运价表字段;
    ->根据模式、公式类型;
    :获取对应统计配置字段;
    ->根据模式、公式类型;
    :获取对应公式字段;
    :选择需要回填的字段;
    ->提交;
    :更新;

stop
@enduml