@startuml
autonumber

participant UploadTimer
participant UploadService
participant DrugCodeUploadSettingService
participant WmsMscService
UploadTimer ->UploadTimer:凌晨六点触发
UploadTimer ->DrugCodeUploadSettingService:获取货品编码设置（①药监码品种为是，②状态为正常）
UploadTimer -> UploadService:传入货品编码设置
UploadService -> UploadTimer:返回当天需上传的货品编码
UploadTimer -> WmsMscService: 获取药监码的扫码信息，传入上次上传时间与当天六点
WmsMscService -> UploadTimer: 按出入库分组返回药监码的扫码信息
UploadTimer -> UploadService : 按模板加工数据
UploadService -> UploadService: 发送邮件
UploadService -> DrugCodeUploadSettingService :更新最后上传时间

@enduml